version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /usr/share/elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  api:
    build: .
    command: >
      api
      --es-host=elasticsearch:9200
      --job-index=tradie-job.0
      --note-index=job-note.0
      --client-index=tradie-client.0
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080
    volumes:
      - ./:/app/
    environment:
      # Add environment variables here
      - EXAMPLE_ENV_VAR=value
networks:
    default:
        external:
            name: tradienwlocal